name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Change this if your Docker Hub repo name is not "comfy-jupyter"
env:
  IMAGE_NAME: comfy-jupyter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check secrets are present
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "Missing secret: DOCKERHUB_USERNAME"; exit 1; fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "Missing secret: DOCKERHUB_TOKEN"; exit 1; fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
